// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package register

import (
	"golang/pkg/mail/gomail"
	"golang/src/register/delivery/http"
	register2 "golang/src/register/service"
	"golang/src/user/repository"
	user2 "golang/src/user/service"

	"gorm.io/gorm"

)

// Injectors from wire.go:

func InitializeService(db *gorm.DB) *register.RegisterHandler {
	userRepository := user.NewUserRepository(db)
	userService := user2.NewUserService(userRepository)
	smtpMail := mail.NewSmtpMail()
	registerService := register2.NewRegisterService(userService, smtpMail)
	registerHandler := register.NewRegisterHandler(registerService)
	return registerHandler
}