// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package book

import (
	"golang/src/book/delivery/http"
	book2 "golang/src/book/repository"
	book3 "golang/src/book/service"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func InitializeService(db *gorm.DB) *book.BookHandler {
	bookRepository := book2.NewBookRepository(db)
	bookService := book3.NewBookService(bookRepository)
	bookHandler := book.NewBookHandler(bookService)
	return bookHandler
}
